// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG1a7lsPiAAc4PCxYx7PU9BYtIvE18-fw',
    appId: '1:467423168153:web:a8b6b821f8656917e85a08',
    messagingSenderId: '467423168153',
    projectId: 'dht11anddht22-14fb9',
    authDomain: 'dht11anddht22-14fb9.firebaseapp.com',
    databaseURL: 'https://dht11anddht22-14fb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dht11anddht22-14fb9.firebasestorage.app',
    measurementId: 'G-1BL86F1XQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdFBsNFZsdn0tTaR2v77Fmx2PQ64wmy0w',
    appId: '1:467423168153:android:c5b78699e32a4aede85a08',
    messagingSenderId: '467423168153',
    projectId: 'dht11anddht22-14fb9',
    databaseURL: 'https://dht11anddht22-14fb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dht11anddht22-14fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSv9_WOuNf9VN657W7VXTcRjRtEXmhcDY',
    appId: '1:467423168153:ios:835bf96a12b6bdc1e85a08',
    messagingSenderId: '467423168153',
    projectId: 'dht11anddht22-14fb9',
    databaseURL: 'https://dht11anddht22-14fb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dht11anddht22-14fb9.firebasestorage.app',
    iosBundleId: 'com.example.flutterWeatherDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSv9_WOuNf9VN657W7VXTcRjRtEXmhcDY',
    appId: '1:467423168153:ios:835bf96a12b6bdc1e85a08',
    messagingSenderId: '467423168153',
    projectId: 'dht11anddht22-14fb9',
    databaseURL: 'https://dht11anddht22-14fb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dht11anddht22-14fb9.firebasestorage.app',
    iosBundleId: 'com.example.flutterWeatherDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG1a7lsPiAAc4PCxYx7PU9BYtIvE18-fw',
    appId: '1:467423168153:web:697517fbfb1a630fe85a08',
    messagingSenderId: '467423168153',
    projectId: 'dht11anddht22-14fb9',
    authDomain: 'dht11anddht22-14fb9.firebaseapp.com',
    databaseURL: 'https://dht11anddht22-14fb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dht11anddht22-14fb9.firebasestorage.app',
    measurementId: 'G-QK65W1YX8H',
  );

}